#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────
# Victoria sandbox watchdog — keeps http://127.0.0.1:$HOST_PORT alive.
#
# Installed as a launchd agent by scripts/setup-watchdog.sh (see that script and
# com.victoria.watchdog.plist.template). Run it directly for a foreground test:
#
#   SBX_NAME=victoria HOST_PORT=8001 ./scripts/victoria-watchdog.sh
#
# WHY: the sbx kit's `startup` service fires ONCE at `sbx run` — it is not a boot
# service. Two things therefore leave :8001 dark with no self-recovery:
#   1. Mac reboot — Docker Desktop auto-starts, but the sandbox does not.
#   2. Docker recycling the sandbox's container mid-session — this kills uvicorn
#      AND the kit's in-VM `while true` supervisor (observed twice: the sandbox
#      still reads "running" while nothing listens, and the in-VM client IP has
#      changed, e.g. 172.17.0.8 -> 172.17.0.6, with no crash in the log).
# A HOST-side watchdog survives both, because it lives outside the VM.
#
# The repair is deliberately the CHEAP path, never a recreate: the sandbox's
# filesystem (the uv py3.11 venv + all deps) survives a recycle, so we only need
# to relaunch uvicorn — seconds, not the ~15-20 min cold `deploy-sandbox.sh`.
# `sbx exec` starts a stopped sandbox first, so one call covers "stopped after
# reboot" and "running but dead inside".
#
# NOT handled on purpose: a MISSING sandbox (removed via `sbx rm`/`sbx reset`).
# That needs a full kit rebuild + mounts, which is `deploy-sandbox.sh`'s job and
# is far too heavy to trigger unattended from a background agent — we log it
# loudly instead.
# ─────────────────────────────────────────────────────────────────────
set -uo pipefail   # NOTE: no -e; a watchdog must never exit on a transient failure

SBX_NAME="${SBX_NAME:-victoria}"
HOST_PORT="${HOST_PORT:-8001}"
REPO_STAGE="${REPO_STAGE:-$HOME/sandboxes/victoria-ai}"
CHECK_INTERVAL="${CHECK_INTERVAL:-30}"     # seconds between health polls
LOG_MAX_BYTES="${LOG_MAX_BYTES:-1048576}"  # self-rotate at ~1 MB (launchd won't)
LOG_FILE="${LOG_FILE:-$HOME/Library/Logs/victoria-watchdog.log}"

log() { printf '%s %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$*"; }

# launchd points stdout/stderr at LOG_FILE and never truncates it. Rotate here so
# a long-lived agent can't fill the disk.
rotate_log_if_big() {
  [ -f "$LOG_FILE" ] || return 0
  local size
  size=$(wc -c < "$LOG_FILE" 2>/dev/null | tr -d ' ') || return 0
  [ "${size:-0}" -gt "$LOG_MAX_BYTES" ] 2>/dev/null && mv -f "$LOG_FILE" "$LOG_FILE.1"
  return 0
}

healthy() { curl -4 -fsS -m 5 -o /dev/null "http://127.0.0.1:${HOST_PORT}/health" 2>/dev/null; }

docker_ready() { docker info >/dev/null 2>&1; }

sandbox_exists() { sbx ls 2>/dev/null | awk '{print $1}' | grep -qx "$SBX_NAME"; }

# The in-VM supervisor. Written into the repo mount (so it's visible inside the
# sandbox at the same absolute path) rather than baked into the kit, so the
# watchdog can repair a sandbox that was created before this script existed.
ensure_runner() {
  local runner="$REPO_STAGE/.victoria-run.sh"
  [ -d "$REPO_STAGE" ] || { log "ERROR: repo stage $REPO_STAGE missing — run ./deploy-sandbox.sh"; return 1; }
  cat > "$runner" <<EOF
#!/bin/sh
# Generated by victoria-watchdog.sh — keeps uvicorn up inside the sandbox.
cd "$REPO_STAGE" || exit 1
export PATH=/usr/local/share/npm-global/bin:\$PATH
while true; do
  /home/agent/venv/bin/python -m uvicorn victoria.main:app --host 0.0.0.0 --port 8000
  echo "[supervisor] uvicorn exited (\$?) — restarting in 3s"
  sleep 3
done
EOF
  chmod 755 "$runner"
}

# Liveness is decided by an in-sandbox HTTP probe, NOT by process matching.
# Reason (learned the hard way): `sbx exec <sbx> -- sh -lc '<cmd>'` gives the
# wrapper shell a cmdline that CONTAINS <cmd>, so a naive `pgrep -f "uvicorn
# victoria.main"` matches the wrapper itself and always reports ALIVE, and the
# matching `pkill -f` makes that shell SIGTERM ITSELF — killing the very process
# that was about to start the supervisor. Where a pattern is unavoidable below we
# use the bracket trick (`uvicorn[ ]victoria.main`), which cannot self-match.
in_sandbox_health() {
  sbx exec "$SBX_NAME" -- sh -lc \
    'curl -s -o /dev/null -w "%{http_code}" -m 5 http://127.0.0.1:8000/health' 2>/dev/null | tail -1
}

repair() {
  log "REPAIR: :$HOST_PORT is down — attempting cheap in-place restart"

  if ! docker_ready; then
    log "  Docker not ready yet (still booting?) — will retry"
    return 1
  fi
  if ! sandbox_exists; then
    log "  ERROR: sandbox '$SBX_NAME' does not exist. A watchdog will not rebuild it"
    log "         (needs a kit pack + mounts). Run: ./deploy-sandbox.sh"
    return 1
  fi
  ensure_runner || return 1

  # `sbx exec` starts the sandbox first if it is stopped, so this probe also covers
  # the "stopped after reboot" case.
  local inner
  inner="$(in_sandbox_health)"
  log "  in-sandbox /health = ${inner:-unreachable}"

  if [ "$inner" = "200" ]; then
    # The app is fine; only the host-side mapping is broken (a container recycle
    # drops it). Re-publishing alone fixes this — do NOT touch the running app.
    log "  app is healthy inside — republishing the host port mapping"
    sbx ports "$SBX_NAME" --unpublish "127.0.0.1:${HOST_PORT}:8000" >/dev/null 2>&1
    sbx ports "$SBX_NAME" --publish   "127.0.0.1:${HOST_PORT}:8000" >/dev/null 2>&1
  else
    # Verify deps survived. If the venv is gone the sandbox was rebuilt from
    # scratch and only a full deploy can fix it — say so rather than thrash.
    if ! sbx exec "$SBX_NAME" -- sh -lc '/home/agent/venv/bin/python -c "import uvicorn, victoria.main"' >/dev/null 2>&1; then
      log "  ERROR: py3.11 venv/deps missing inside the sandbox — run ./deploy-sandbox.sh"
      return 1
    fi
    # TWO SEPARATE exec calls, deliberately. The cleanup patterns must not appear
    # literally in their own command line, and the runner's PATH contains the text
    # "victoria-run" — so a combined command would match itself and SIGTERM the
    # wrapper shell before it ever reached setsid (this bit us twice). Keeping the
    # kill and the launch in different exec calls makes self-matching impossible.
    sbx exec "$SBX_NAME" -- sh -lc \
      "pkill -f 'uvicorn[ ]victoria.main' 2>/dev/null; pkill -f 'victoria[-]run[.]sh' 2>/dev/null; exit 0" \
      >/dev/null 2>&1
    # setsid + nohup so the supervisor is re-parented to init and outlives this
    # `sbx exec` session (a plain `&` job dies with the exec).
    sbx exec "$SBX_NAME" -- sh -lc \
      "setsid nohup sh '$REPO_STAGE/.victoria-run.sh' >> /tmp/victoria.log 2>&1 </dev/null & sleep 2; exit 0" \
      >/dev/null 2>&1
    log "  supervised uvicorn relaunched"
    sbx ports "$SBX_NAME" --publish "127.0.0.1:${HOST_PORT}:8000" >/dev/null 2>&1
  fi
  log "  port 127.0.0.1:${HOST_PORT} -> 8000 asserted"

  # App import is slow (chromadb/torch); give it generous headroom.
  local i
  for i in $(seq 1 60); do
    healthy && { log "  RECOVERED: http://127.0.0.1:${HOST_PORT} is serving"; return 0; }
    sleep 5
  done
  log "  still down after ~5 min — check: sbx exec $SBX_NAME -- tail -30 /tmp/victoria.log"
  return 1
}

log "watchdog start (sandbox=$SBX_NAME port=$HOST_PORT interval=${CHECK_INTERVAL}s stage=$REPO_STAGE)"
was_healthy=""
while true; do
  rotate_log_if_big
  if healthy; then
    # Only log transitions, so an idle watchdog stays quiet in the log.
    [ "$was_healthy" = "yes" ] || log "OK: http://127.0.0.1:${HOST_PORT} healthy"
    was_healthy="yes"
  else
    was_healthy="no"
    repair
  fi
  sleep "$CHECK_INTERVAL"
done
